// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_nx8qW71dQA6Mole_wot8SkEsbfGH_Y',
    appId: '1:620657075933:web:cdf572d8995679215d5d34',
    messagingSenderId: '620657075933',
    projectId: 'nexushub-472d7',
    authDomain: 'nexushub-472d7.firebaseapp.com',
    storageBucket: 'nexushub-472d7.firebasestorage.app',
    measurementId: 'G-2L0GWD56RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVU1rMtlxW1VRtabIe8vOQ-GLFFD9CxVQ',
    appId: '1:620657075933:android:2ab03340d6bae6ec5d5d34',
    messagingSenderId: '620657075933',
    projectId: 'nexushub-472d7',
    storageBucket: 'nexushub-472d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHJ9rkoFZQIjq80IaWmkFfeI29cpvUPE',
    appId: '1:620657075933:ios:1cb20800b61fb0645d5d34',
    messagingSenderId: '620657075933',
    projectId: 'nexushub-472d7',
    storageBucket: 'nexushub-472d7.firebasestorage.app',
    iosBundleId: 'com.example.nexusHubFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHJ9rkoFZQIjq80IaWmkFfeI29cpvUPE',
    appId: '1:620657075933:ios:1cb20800b61fb0645d5d34',
    messagingSenderId: '620657075933',
    projectId: 'nexushub-472d7',
    storageBucket: 'nexushub-472d7.firebasestorage.app',
    iosBundleId: 'com.example.nexusHubFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn_nx8qW71dQA6Mole_wot8SkEsbfGH_Y',
    appId: '1:620657075933:web:51e571872b22a8b35d5d34',
    messagingSenderId: '620657075933',
    projectId: 'nexushub-472d7',
    authDomain: 'nexushub-472d7.firebaseapp.com',
    storageBucket: 'nexushub-472d7.firebasestorage.app',
    measurementId: 'G-MPQF27M3EB',
  );
}
